// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BotService exposes bot control to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBotStatus returns the current bot status.
 */
export function GetBotStatus(): $CancellablePromise<$models.BotStatus> {
    return $Call.ByID(2094595390).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OnBotEvent emits a bot event to the frontend.
 */
export function OnBotEvent(event: $models.BotEvent): $CancellablePromise<void> {
    return $Call.ByID(1999249023, event);
}

/**
 * SetApplication stores the Wails app reference.
 */
export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3370706811, app);
}

/**
 * StartBot connects to the OneBot WebSocket endpoint.
 */
export function StartBot(): $CancellablePromise<void> {
    return $Call.ByID(3782792060);
}

/**
 * StopBot disconnects from the OneBot endpoint.
 */
export function StopBot(): $CancellablePromise<void> {
    return $Call.ByID(3299391958);
}

// Private type creation functions
const $$createType0 = $models.BotStatus.createFrom;
