// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService exposes direct LLM chat to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory clears the GUI chat history.
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(2224255187);
}

/**
 * GetHistory returns the GUI chat history.
 * @returns {$CancellablePromise<$models.ChatMessage[]>}
 */
export function GetHistory() {
    return $Call.ByID(1405544464).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SendMessage sends a message to the LLM and returns the assistant reply.
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SendMessage(content) {
    return $Call.ByID(1605358217, content);
}

// Private type creation functions
const $$createType0 = $models.ChatMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
