// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService exposes direct LLM chat to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory clears the GUI chat history.
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(2224255187);
}

/**
 * GetHistory returns the GUI chat history.
 */
export function GetHistory(): $CancellablePromise<$models.ChatMessage[]> {
    return $Call.ByID(1405544464).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SendMessage sends a text message to the LLM and returns the assistant reply.
 */
export function SendMessage(content: string): $CancellablePromise<string> {
    return $Call.ByID(1605358217, content);
}

/**
 * SendVisionMessage sends a message with image URLs, using the vision model fallback if needed.
 */
export function SendVisionMessage(text: string, imageURLs: string[]): $CancellablePromise<string> {
    return $Call.ByID(1646668425, text, imageURLs);
}

/**
 * UpdateConfig refreshes the service's config copy.
 */
export function UpdateConfig(cfg: config$0.LLMConfig): $CancellablePromise<void> {
    return $Call.ByID(3150132015, cfg);
}

// Private type creation functions
const $$createType0 = $models.ChatMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
