// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * GetConfig returns the current configuration.
 */
export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(748383354).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveConfig persists the configuration and updates the in-memory copy.
 */
export function SaveConfig(cfg: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(903871999, cfg);
}

/**
 * TestLLMConnection sends a minimal request to validate LLM connectivity.
 */
export function TestLLMConnection(baseURL: string, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(409124323, baseURL, apiKey);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
