// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes configuration management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the current configuration.
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(748383354).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveConfig persists the configuration and updates the in-memory copy.
 * @param {config$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(903871999, cfg);
}

/**
 * TestLLMConnection validates LLM connectivity by listing available models.
 * We intentionally avoid sending a chat completion here because many
 * OpenAI-compatible gateways or reasoning models reject simple test prompts
 * with opaque 400 errors (e.g. "Param Incorrect"). Listing models is a
 * reliable, read-only way to verify the URL and API key.
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<$models.TestLLMResult>}
 */
export function TestLLMConnection(baseURL, apiKey) {
    return $Call.ByID(409124323, baseURL, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $models.TestLLMResult.createFrom;
