// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * BotEvent is emitted to the frontend.
 */
export class BotEvent {
    /**
     * Creates a new BotEvent instance.
     * @param {Partial<BotEvent>} [$$source = {}] - The source object to create the BotEvent.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {json$0.RawMessage}
             */
            this["data"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BotEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotEvent(/** @type {Partial<BotEvent>} */($$parsedSource));
    }
}

/**
 * BotStatus is the runtime status of the bot.
 */
export class BotStatus {
    /**
     * Creates a new BotStatus instance.
     * @param {Partial<BotStatus>} [$$source = {}] - The source object to create the BotStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("connectedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectedAt"] = "";
        }
        if (!("oneBotURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["oneBotURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BotStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotStatus(/** @type {Partial<BotStatus>} */($$parsedSource));
    }
}

/**
 * ChatMessage represents a message in the GUI chat history.
 */
export class ChatMessage {
    /**
     * Creates a new ChatMessage instance.
     * @param {Partial<ChatMessage>} [$$source = {}] - The source object to create the ChatMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage(/** @type {Partial<ChatMessage>} */($$parsedSource));
    }
}

/**
 * LLMModelInfo is returned to the frontend.
 */
export class LLMModelInfo {
    /**
     * Creates a new LLMModelInfo instance.
     * @param {Partial<LLMModelInfo>} [$$source = {}] - The source object to create the LLMModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("vision" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vision"] = false;
        }
        if (!("tools" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tools"] = false;
        }
        if (!("reasoning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reasoning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMModelInfo(/** @type {Partial<LLMModelInfo>} */($$parsedSource));
    }
}

/**
 * TestLLMResult combines connection test with model list.
 */
export class TestLLMResult {
    /**
     * Creates a new TestLLMResult instance.
     * @param {Partial<TestLLMResult>} [$$source = {}] - The source object to create the TestLLMResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {LLMModelInfo[]}
             */
            this["models"] = [];
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestLLMResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestLLMResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        return new TestLLMResult(/** @type {Partial<TestLLMResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = LLMModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
