// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * BotEvent is emitted to the frontend.
 */
export class BotEvent {
    "type": string;
    "data": json$0.RawMessage;

    /** Creates a new BotEvent instance. */
    constructor($$source: Partial<BotEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): BotEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotEvent($$parsedSource as Partial<BotEvent>);
    }
}

/**
 * BotStatus is the runtime status of the bot.
 */
export class BotStatus {
    "running": boolean;
    "connectedAt": string;
    "oneBotURL": string;

    /** Creates a new BotStatus instance. */
    constructor($$source: Partial<BotStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("connectedAt" in $$source)) {
            this["connectedAt"] = "";
        }
        if (!("oneBotURL" in $$source)) {
            this["oneBotURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BotStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotStatus($$parsedSource as Partial<BotStatus>);
    }
}

/**
 * ChatMessage represents a message in the GUI chat history.
 */
export class ChatMessage {
    "role": string;
    "content": string;
    "timestamp": number;

    /** Creates a new ChatMessage instance. */
    constructor($$source: Partial<ChatMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage($$parsedSource as Partial<ChatMessage>);
    }
}

/**
 * LLMModelInfo is returned to the frontend.
 */
export class LLMModelInfo {
    "id": string;
    "vision": boolean;
    "tools": boolean;
    "reasoning": boolean;

    /** Creates a new LLMModelInfo instance. */
    constructor($$source: Partial<LLMModelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("vision" in $$source)) {
            this["vision"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = false;
        }
        if (!("reasoning" in $$source)) {
            this["reasoning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LLMModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMModelInfo($$parsedSource as Partial<LLMModelInfo>);
    }
}

/**
 * TestLLMResult combines connection test with model list.
 */
export class TestLLMResult {
    "success": boolean;
    "models": LLMModelInfo[];
    "error": string;

    /** Creates a new TestLLMResult instance. */
    constructor($$source: Partial<TestLLMResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestLLMResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TestLLMResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        return new TestLLMResult($$parsedSource as Partial<TestLLMResult>);
    }
}

// Private type creation functions
const $$createType0 = LLMModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
