// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BotConfig holds the OneBot adapter connection settings.
 */
export class BotConfig {
    /**
     * Creates a new BotConfig instance.
     * @param {Partial<BotConfig>} [$$source = {}] - The source object to create the BotConfig.
     */
    constructor($$source = {}) {
        if (!("onebot_ws_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["onebot_ws_url"] = "";
        }
        if (!("admin_qq" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["admin_qq"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BotConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotConfig(/** @type {Partial<BotConfig>} */($$parsedSource));
    }
}

/**
 * Config is the top-level application configuration.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("llm" in $$source)) {
            /**
             * @member
             * @type {LLMConfig}
             */
            this["llm"] = (new LLMConfig());
        }
        if (!("bot" in $$source)) {
            /**
             * @member
             * @type {BotConfig}
             */
            this["bot"] = (new BotConfig());
        }
        if (!("search" in $$source)) {
            /**
             * @member
             * @type {SearchConfig}
             */
            this["search"] = (new SearchConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("llm" in $$parsedSource) {
            $$parsedSource["llm"] = $$createField0_0($$parsedSource["llm"]);
        }
        if ("bot" in $$parsedSource) {
            $$parsedSource["bot"] = $$createField1_0($$parsedSource["bot"]);
        }
        if ("search" in $$parsedSource) {
            $$parsedSource["search"] = $$createField2_0($$parsedSource["search"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * LLMConfig holds the OpenAI-compatible LLM settings.
 */
export class LLMConfig {
    /**
     * Creates a new LLMConfig instance.
     * @param {Partial<LLMConfig>} [$$source = {}] - The source object to create the LLMConfig.
     */
    constructor($$source = {}) {
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("system_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["system_prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfig(/** @type {Partial<LLMConfig>} */($$parsedSource));
    }
}

/**
 * SearchConfig holds the web search provider settings.
 */
export class SearchConfig {
    /**
     * Creates a new SearchConfig instance.
     * @param {Partial<SearchConfig>} [$$source = {}] - The source object to create the SearchConfig.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("tavily_api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tavily_api_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchConfig(/** @type {Partial<SearchConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = LLMConfig.createFrom;
const $$createType1 = BotConfig.createFrom;
const $$createType2 = SearchConfig.createFrom;
