// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BotConfig holds the OneBot adapter connection settings.
 */
export class BotConfig {
    "onebot_ws_url": string;
    "admin_qq": string;

    /** Creates a new BotConfig instance. */
    constructor($$source: Partial<BotConfig> = {}) {
        if (!("onebot_ws_url" in $$source)) {
            this["onebot_ws_url"] = "";
        }
        if (!("admin_qq" in $$source)) {
            this["admin_qq"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BotConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotConfig($$parsedSource as Partial<BotConfig>);
    }
}

/**
 * Config is the top-level application configuration.
 */
export class Config {
    "llm": LLMConfig;
    "bot": BotConfig;
    "search": SearchConfig;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("llm" in $$source)) {
            this["llm"] = (new LLMConfig());
        }
        if (!("bot" in $$source)) {
            this["bot"] = (new BotConfig());
        }
        if (!("search" in $$source)) {
            this["search"] = (new SearchConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("llm" in $$parsedSource) {
            $$parsedSource["llm"] = $$createField0_0($$parsedSource["llm"]);
        }
        if ("bot" in $$parsedSource) {
            $$parsedSource["bot"] = $$createField1_0($$parsedSource["bot"]);
        }
        if ("search" in $$parsedSource) {
            $$parsedSource["search"] = $$createField2_0($$parsedSource["search"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * LLMConfig holds the OpenAI-compatible LLM settings.
 */
export class LLMConfig {
    "base_url": string;
    "api_key": string;
    "model": string;
    "vision_model": string;
    "reasoning_effort": string;
    "system_prompt": string;
    "model_capabilities": { [_ in string]?: ModelCapability };

    /** Creates a new LLMConfig instance. */
    constructor($$source: Partial<LLMConfig> = {}) {
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("vision_model" in $$source)) {
            this["vision_model"] = "";
        }
        if (!("reasoning_effort" in $$source)) {
            this["reasoning_effort"] = "";
        }
        if (!("system_prompt" in $$source)) {
            this["system_prompt"] = "";
        }
        if (!("model_capabilities" in $$source)) {
            this["model_capabilities"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LLMConfig {
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("model_capabilities" in $$parsedSource) {
            $$parsedSource["model_capabilities"] = $$createField6_0($$parsedSource["model_capabilities"]);
        }
        return new LLMConfig($$parsedSource as Partial<LLMConfig>);
    }
}

/**
 * ModelCapability stores per-model overrides detected by the user.
 */
export class ModelCapability {
    "vision": boolean;
    "tools": boolean;
    "reasoning": boolean;
    "max_context": number;

    /** Creates a new ModelCapability instance. */
    constructor($$source: Partial<ModelCapability> = {}) {
        if (!("vision" in $$source)) {
            this["vision"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = false;
        }
        if (!("reasoning" in $$source)) {
            this["reasoning"] = false;
        }
        if (!("max_context" in $$source)) {
            this["max_context"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelCapability instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelCapability {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelCapability($$parsedSource as Partial<ModelCapability>);
    }
}

/**
 * SearchConfig holds the web search provider settings.
 */
export class SearchConfig {
    "provider": string;
    "tavily_api_key": string;

    /** Creates a new SearchConfig instance. */
    constructor($$source: Partial<SearchConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("tavily_api_key" in $$source)) {
            this["tavily_api_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchConfig($$parsedSource as Partial<SearchConfig>);
    }
}

// Private type creation functions
const $$createType0 = LLMConfig.createFrom;
const $$createType1 = BotConfig.createFrom;
const $$createType2 = SearchConfig.createFrom;
const $$createType3 = ModelCapability.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
